# Generated by Django 5.2.14 on 2026-07-30 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicetoken',
            new_name='device_toke_user_id_25a987_idx',
            old_name='device_toke_user_id_0f8f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='devicetoken',
            new_name='device_toke_municip_5fbb30_idx',
            old_name='device_toke_municip_8a0d0b_idx',
        ),
    ]
