# Generated by Django 5.2.14 on 2026-08-26 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alertpreference_pushtoken_delete_devicetoken_and_more'),
        ('sensors', '0005_add_sensor_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('last_level', models.CharField(choices=[('none', 'none'), ('possible_slip', 'possible_slip'), ('increased_ice', 'increased_ice'), ('acute_ice', 'acute_ice')], max_length=20)),
                ('last_sent_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_notification_states', to='sensors.sensor')),
            ],
            options={
                'indexes': [models.Index(fields=['sensor', 'user_id'], name='devices_pus_sensor__d1ea6a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'sensor'), name='unique_push_state_per_user_sensor')],
            },
        ),
    ]
