# Generated by Django 5.2.14 on 2026-10-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsageAnalyticsInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.UUIDField(db_index=True, unique=True)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('days', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_upload_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usage analytics installation',
                'verbose_name_plural': 'Usage analytics installations',
            },
        ),
    ]
