# Generated by Django 5.2.14 on 2026-05-12 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipalities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('sensor_type', models.CharField(choices=[('standard', 'Standard'), ('additional', 'Additional')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='municipalities.municipality')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
