# Generated by Django 5.2.14 on 2026-06-03 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='municipality',
            field=models.ForeignKey(blank=True, help_text='Optional; can be assigned later in admin. Not required for webhook ingestion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='municipalities.municipality'),
        ),
    ]
