# Generated by Django 5.2.14 on 2026-06-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_municipality_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='device_name',
            field=models.CharField(blank=True, db_index=True, help_text='Stable LoRaWAN deviceName, e.g. MUB-TPK-0001-N50.22764-E11.76708.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='display_name',
            field=models.CharField(blank=True, help_text='Human-readable sensor label for maps and admin views.', max_length=255),
        ),
        migrations.AddField(
            model_name='sensor',
            name='location_description',
            field=models.TextField(blank=True, help_text='Road section, station, crossing or other installation details.'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='operator_name',
            field=models.CharField(blank=True, help_text='Responsible municipality/organization from the metadata list.', max_length=255),
        ),
        migrations.AddField(
            model_name='sensor',
            name='what3words',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
