# Generated by Django 5.2.14 on 2026-06-08 08:52

from django.db import migrations


def backfill_device_name(apps, schema_editor):
    Sensor = apps.get_model('sensors', 'Sensor')
    SensorReading = apps.get_model('readings', 'SensorReading')

    for sensor in Sensor.objects.filter(device_name__isnull=True):
        latest_reading = (
            SensorReading.objects.filter(sensor_id=sensor.id)
            .exclude(device_name='')
            .order_by('-timestamp')
            .first()
        )
        if latest_reading:
            sensor.device_name = latest_reading.device_name
        elif '-TPK-' in sensor.name:
            sensor.device_name = sensor.name
        else:
            continue
        sensor.save(update_fields=['device_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_add_sensor_metadata'),
        ('readings', '0005_add_device_name'),
    ]

    operations = [
        migrations.RunPython(backfill_device_name, migrations.RunPython.noop),
    ]
