# Generated by Django 5.2.14 on 2026-06-10 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_backfill_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='sensor',
            name='updated_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
