# Generated by Django 5.2.14 on 2026-05-12 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('air_temperature', models.FloatField()),
                ('road_temperature', models.FloatField()),
                ('humidity', models.FloatField(help_text='Relative humidity in percent.')),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor', '-timestamp'], name='readings_se_sensor__17d9a0_idx'), models.Index(fields=['sensor', 'timestamp'], name='readings_se_sensor__471f0c_idx')],
            },
        ),
    ]
