# Generated by Django 5.2.14 on 2026-06-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='air_humidity_radiation_shield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='air_humidity_unshielded',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='air_temperature_radiation_shield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='air_temperature_unshielded',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='battery_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='es_geo_shape',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='event_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='reported_dew_point',
            field=models.FloatField(blank=True, help_text='Dew point as reported by upstream payload; API dew_point is computed.', null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='rx_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='sensor_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='sid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
