# Generated by Django 5.2.14 on 2026-06-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_structured_payload_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='es_geo_shape',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='sid',
        ),
    ]
