# Generated by Django 5.2.14 on 2026-06-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0003_remove_payload_metadata_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='rx_time',
        ),
    ]
