# Generated by Django 5.2.14 on 2026-06-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0004_remove_rx_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='device_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
