# Generated by Django 5.2.14 on 2026-05-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('geo_boundary', models.JSONField(help_text='GeoJSON polygon or multipolygon describing municipality border.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
